import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { PortBroker } from "../src/runIsolation/portBroker.mjs";
import { ProcessSupervisor } from "../src/runIsolation/processSupervisor.mjs";
import { RunIsolationExecutionCoordinator } from "../src/runIsolation/runIsolationExecutionCoordinator.mjs";
import { fixture, prepareInput, session, toolsetFixture } from "./runIsolationTestHelpers.mjs";

test("timeout and crash signals finalize as infrastructure failures without leaked leases",async t=>{for(const [name,args,timeoutMilliseconds] of [["timeout",["-e","setInterval(()=>{},1000)"],25],["crash",["-e","process.kill(process.pid,\"SIGKILL\")"],null]]){const {service}=await fixture(t,{serviceOptions:{commandResolver:async(_ref,context)=>({executable:process.execPath,args,cwd:context.runRoot,role:name,...(timeoutMilliseconds?{timeoutMilliseconds}:{})})}});const {context}=await service.prepareRun(prepareInput({idempotencyKey:`prepare-${name}`}),session);const run=service.store.getRun(context.runId);const receipt=await service.execute({runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,commandDescriptorRef:`command:${name}`,idempotencyKey:`execute:${name}`},session);assert.equal(receipt.state,"failed");assert.equal(receipt.outcome,"infrastructure_failed");assert.equal(service.store.latestCleanupReceipt(run.runId).outcome,"retained");assert.equal(service.store.activeLeases(run.runId).length,0)}});

test("PortBroker holds 50 unique loopback listener FDs without bind-close-rebind",async()=>{const broker=new PortBroker();try{const reservations=await Promise.all(Array.from({length:50},(_,i)=>broker.reserve({runId:`run:${i}`})));assert.equal(new Set(reservations.map(x=>x.port)).size,50);assert.equal(reservations.every(x=>x.host==="127.0.0.1"&&x.listenFD>=0&&broker.isOpen(x.handleId)),true)}finally{await broker.close()}});
test("PID reuse and foreign executable never receive a signal",async()=>{const observations=new Map([[42,{kernelStartTime:"new",executableRealpath:"/bin/foreign"}]]);const signals=[];const supervisor=new ProcessSupervisor({observe:async pid=>observations.get(pid)??null,signal:(...args)=>signals.push(args)});let result=await supervisor.terminate({pid:42,kernelStartTime:"old",executableHash:"x"});assert.equal(result.status,"pidReused");observations.set(42,{kernelStartTime:"old",executableRealpath:"/bin/foreign"});result=await supervisor.terminate({pid:42,kernelStartTime:"old",executableHash:"0".repeat(64)});assert.equal(result.status,"foreign");assert.deepEqual(signals,[])});
test("EPERM is indeterminate and fails closed",async()=>{const supervisor=new ProcessSupervisor({observe:async()=>({kernelStartTime:"same",executableRealpath:"/bin/test"}),signal:()=>{throw Object.assign(new Error("no"),{code:"EPERM"})}});const {createHash}=await import("node:crypto");const executableHash=createHash("sha256").update("/bin/test").digest("hex");const result=await supervisor.terminate({pid:8,kernelStartTime:"same",executableHash});assert.equal(result.status,"indeterminate")});
test("SIGKILL is sent only after a second matching identity observation",async()=>{let alive=true;let observations=0;const signals=[];const supervisor=new ProcessSupervisor({observe:async()=>{observations++;return alive?{kernelStartTime:"same",executableRealpath:"/bin/test"}:null},signal:(_pid,signal)=>{signals.push(signal);if(signal==="SIGKILL")alive=false}});const {createHash}=await import("node:crypto");const executableHash=createHash("sha256").update("/bin/test").digest("hex");const result=await supervisor.terminate({pid:9,kernelStartTime:"same",executableHash},{graceMilliseconds:0});assert.equal(result.status,"matchedExited");assert.deepEqual(signals,["SIGTERM","SIGKILL"]);assert.ok(observations>=2)});
test("kill9 fault leaves an owned child as ESRCH and never matches a reused PID",async()=>{const child=spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"ignore"});const supervisor=new ProcessSupervisor();try{const identity=await supervisor.identity(child.pid,{runToken:"fault-token",fencingToken:7});assert.ok(identity?.kernelStartTime);child.kill("SIGKILL");await new Promise(resolve=>child.once("exit",resolve));const reconciled=await supervisor.reconcile({pid:child.pid,kernelStartTime:identity.kernelStartTime,executableHash:identity.executableRealpathHash});assert.equal(reconciled.status,"esrch")}finally{if(child.exitCode===null)child.kill("SIGKILL")}});
test("execute completion and cancel reclaim process, port, handle, heartbeat and credential resources",async t=>{const {service}=await fixture(t,{serviceOptions:{commandResolver:async(_ref,context)=>({executable:process.execPath,args:["-e","setInterval(()=>{},1000)"],cwd:context.runRoot,role:"worker"})}});const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-process-lifecycle"}),session);let run=service.store.getRun(context.runId);const completion=service.execute({runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,commandDescriptorRef:"command:test",idempotencyKey:"execute-process"},session);for(let i=0;i<100&&service.store.getRun(run.runId).state!=="running";i++)await new Promise(resolve=>setTimeout(resolve,10));run=service.store.getRun(run.runId);const processRow=service.store.processes(run.runId)[0];assert.ok(processRow.pid>0);assert.equal(service.store.db.prepare("SELECT bound_pid FROM port_leases WHERE run_id=?").get(run.runId).bound_pid,processRow.pid);const cancelled=await service.cancel({runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken},session);assert.equal((await completion).receiptHash,cancelled.receiptHash);assert.equal(cancelled.outcome,"cancelled");assert.equal(service.store.latestCleanupReceipt(run.runId).outcome,"retained");assert.equal(service.store.activeLeases(run.runId).length,0);assert.equal(service.store.db.prepare("SELECT state FROM port_leases WHERE run_id=?").get(run.runId).state,"released");assert.equal(service.store.processes(run.runId)[0].state,"exited");assert.equal(service.portBroker.isOpen(context.serverHandleId),false);assert.equal(service.runtimeSecrets.has(run.runId),false)});
test("normal success and nonzero failure events automatically finalize and apply cleanup policy",async t=>{for(const [code,state,outcome,cleanup] of [[0,"completed","passed","cleaned"],[7,"failed","failed","retained"]]){const {service}=await fixture(t,{serviceOptions:{commandResolver:async(_ref,context)=>({executable:process.execPath,args:["-e",`process.exit(${code})`],cwd:context.runRoot,role:`worker-${code}`})}});const {context}=await service.prepareRun(prepareInput({idempotencyKey:`prepare-exit-${code}`}),session);const run=service.store.getRun(context.runId);const receipt=await service.execute({runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,commandDescriptorRef:`command:${code}`,idempotencyKey:`execute:${code}`},session);assert.equal(receipt.state,state);assert.equal(receipt.outcome,outcome);assert.equal(service.store.latestCleanupReceipt(run.runId).outcome,cleanup);assert.equal(service.store.activeLeases(run.runId).length,0)}});
test("an owned child that performs an in-place exec finalizes from its exact child handle",async t=>{const {service}=await fixture(t,{serviceOptions:{commandResolver:async(_ref,context)=>({executable:"/usr/bin/env",args:[process.execPath,"-e","setTimeout(()=>process.exit(0),25)"],cwd:context.runRoot,role:"exec-replacement"})}});const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-exec-replacement"}),session);const run=service.store.getRun(context.runId);const receipt=await service.execute({runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,commandDescriptorRef:"command:exec-replacement",idempotencyKey:"execute:exec-replacement"},session);assert.equal(receipt.state,"completed");assert.equal(receipt.outcome,"passed");assert.equal(service.store.latestCleanupReceipt(run.runId).outcome,"cleaned")});
test("production Port exposes prepareRun-execute-cancel-cleanup and emits only Run v6/Cleanup v4",async t=>{const {service}=await fixture(t);const port=new RunIsolationExecutionCoordinator({service});const prepared=await port.prepareRun(prepareInput({idempotencyKey:"production-port-v6"}),session);const runReceipt=await port.execute({runContext:prepared.context,descriptor:{executable:process.execPath,args:["-e","process.exit(0)"],cwd:prepared.context.runRoot,role:"production-port"},idempotencyKey:"production-port-v6:execute"},session);const cleanupReceipt=service.store.latestCleanupReceipt(prepared.context.runId);assert.equal(runReceipt.schemaVersion,6);assert.equal(runReceipt.outcome,"passed");assert.equal(cleanupReceipt.schemaVersion,4);assert.equal(cleanupReceipt.outcome,"cleaned");assert.equal(typeof port.cancel,"function");assert.equal(typeof port.cleanup,"function")});

test("one Toolset v3 receipt safely serves 20 concurrent Run v6 operations",async t=>{const {service,root}=await fixture(t);const port=new RunIsolationExecutionCoordinator({service});const {authority,snapshotRef,receipt,pointer}=toolsetFixture();const resolver=async id=>{await new Promise(resolve=>setImmediate(resolve));return id===receipt.receiptId?receipt:null};const results=await Promise.all(Array.from({length:20},(_,index)=>port.runCommand({prepare:prepareInput({sourceAware:true,toolsetRequired:true,repositorySourceSnapshotReceiptRef:snapshotRef,toolsetValidationReceiptPointer:pointer,idempotencyKey:`shared-toolset-${index}`}),session:authority,toolsetReceiptResolver:resolver,descriptor:{executable:process.execPath,args:["-e","process.exit(0)"],cwd:root,role:`shared-toolset-${index}`}})));assert.equal(results.length,20);assert.equal(results.every(result=>result.runReceipt.schemaVersion===6&&result.runReceipt.outcome==="passed"&&result.cleanupReceipt.schemaVersion===4&&result.cleanupReceipt.outcome==="cleaned"),true)});

test("Toolset resolver failure and cancellation release only their operation scope",async t=>{const {service,root}=await fixture(t);const port=new RunIsolationExecutionCoordinator({service});const {authority,snapshotRef,receipt,pointer}=toolsetFixture({receiptId:"toolset_validation_receipt:release"});const prepare=index=>prepareInput({sourceAware:true,toolsetRequired:true,repositorySourceSnapshotReceiptRef:snapshotRef,toolsetValidationReceiptPointer:pointer,idempotencyKey:`resolver-release-${index}`});await assert.rejects(port.prepareRun(prepare("failure"),authority,{toolsetReceiptResolver:async()=>{throw new Error("resolver failed")}}),/resolver failed/);const goodResolver=async id=>id===receipt.receiptId?receipt:null;const prepared=await port.prepareRun(prepare("cancel"),authority,{toolsetReceiptResolver:goodResolver});const completion=port.execute({runContext:prepared.context,descriptor:{executable:process.execPath,args:["-e","setInterval(()=>{},1000)"],cwd:root,role:"resolver-cancel"},idempotencyKey:"resolver-release-cancel:execute",toolsetReceiptResolver:goodResolver},authority);for(let index=0;index<100&&service.inspect(prepared.context.runId,authority).state!=="running";index++)await new Promise(resolve=>setTimeout(resolve,10));const running=service.inspect(prepared.context.runId,authority);await port.cancel({runId:running.runId,expectedResourceVersion:running.resourceVersion,fencingToken:running.fencingToken},authority);assert.equal((await completion).outcome,"cancelled");const after=await port.runCommand({prepare:prepare("after"),session:authority,toolsetReceiptResolver:goodResolver,descriptor:{executable:process.execPath,args:["-e","process.exit(0)"],cwd:root,role:"resolver-after"}});assert.equal(after.runReceipt.outcome,"passed")});
