import test from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { RunIsolationAuthorityResolver } from "../src/runIsolation/runIsolationAuthorityResolver.mjs";
import { startupRef, toolsetFixture } from "./runIsolationTestHelpers.mjs";

test("only RunIsolation internals own Store, PortBroker and SafeDeletionExecutor",async()=>{const sourceRoot=new URL("../src/",import.meta.url);const violations=[];async function walk(url){for(const entry of await readdir(url,{withFileTypes:true})){const child=new URL(`${entry.name}${entry.isDirectory()?"/":""}`,url);if(entry.isDirectory()){if(entry.name!=="runIsolation")await walk(child);continue}if(!entry.name.endsWith(".mjs"))continue;const text=await readFile(child,"utf8");if(/\b(?:RunIsolationStore|PortBroker|SafeDeletionExecutor)\b/.test(text))violations.push(child.pathname)}}await walk(sourceRoot);assert.deepEqual(violations,[])});
test("public index exposes provider-neutral service without concrete Provider adapters",async()=>{const text=await readFile(new URL("../src/runIsolation/index.mjs",import.meta.url),"utf8");assert.match(text,/RunIsolationService/);assert.doesNotMatch(text,/codex|claude|openclacky/i)});
test("production server and Project Toolset force Run v6 through an injected authority Port",async()=>{const [server,composition,toolset,coordinator]=await Promise.all([readFile(new URL("../src/server.mjs",import.meta.url),"utf8"),readFile(new URL("../src/application/projectToolsetProductionComposition.mjs",import.meta.url),"utf8"),readFile(new URL("../src/runtime/projectToolsetManager.mjs",import.meta.url),"utf8"),readFile(new URL("../src/runIsolation/runIsolationExecutionCoordinator.mjs",import.meta.url),"utf8")]);assert.match(server,/new RunIsolationExecutionCoordinator/);assert.match(server,/new RunIsolationAuthorityResolver/);assert.match(server,/runIsolationAuthorityResolver\.resolve/);assert.match(composition,/binding\.worktreeId !== startup\.worktreeId/);assert.match(composition,/assertRunAuthorityRequest\(request, authority\)/);assert.match(server,/runIsolationCoordinator\.initialize\(\)/);assert.match(server,/PROJECT_TOOLSET_ISOLATED_ACTIONS\.includes\(action\)/);assert.doesNotMatch(server,/join\(runIsolationDataRoot,\s*["']authorities["']|authorityPath|input\.runIsolation|CORPTIE_RUN_ISOLATION_V3|CORPTIE_RUN_ISOLATION_ENABLED/);assert.match(toolset,/RunIsolation authority is required/);assert.match(toolset,/runIsolationCoordinator\.runCommand/);assert.match(toolset,/resolveValidationReceipt/);for(const phase of ["prepareRun","execute","cancel","cleanup"])assert.match(coordinator,new RegExp(`async ${phase}\\b`))});

test("authority Port is closed, binding-scoped and fail closed",async()=>{const toolset=toolsetFixture();const request={logicalSessionId:toolset.authority.logicalSessionId,taskId:toolset.authority.taskId,repositoryId:toolset.authority.repositoryId,worktreeId:toolset.authority.worktreeId,action:"build",bindingId:"binding:test",bindingGeneration:7};const result={...request};delete result.action;Object.assign(result,{startupBindingReceiptRef:startupRef,repositorySourceSnapshotReceiptRef:toolset.snapshotRef,toolsetValidationReceiptPointer:toolset.pointer});await assert.rejects(new RunIsolationAuthorityResolver().resolve(request),{code:"DEPENDENCY_CONTRACT_UNRESOLVED"});await assert.rejects(new RunIsolationAuthorityResolver({resolveAuthority:async()=>null}).resolve(request),{code:"DEPENDENCY_CONTRACT_UNRESOLVED"});await assert.rejects(new RunIsolationAuthorityResolver({resolveAuthority:async()=>({...result,extra:true})}).resolve(request),{code:"RUN_AUTHORITY_SCHEMA_INVALID"});await assert.rejects(new RunIsolationAuthorityResolver({resolveAuthority:async()=>({...result,bindingGeneration:6})}).resolve(request),{code:"STARTUP_BINDING_STALE"});for(const field of ["taskId","worktreeId"]){await assert.rejects(new RunIsolationAuthorityResolver({resolveAuthority:async()=>({...result,[field]:`${field}:wrong`})}).resolve(request),{code:"RUN_UNAUTHORIZED"})}await assert.rejects(new RunIsolationAuthorityResolver({resolveAuthority:async()=>result}).resolve({...request,unexpected:true}),{code:"RUN_AUTHORITY_SCHEMA_INVALID"});const resolved=await new RunIsolationAuthorityResolver({resolveAuthority:async(input)=>{assert.deepEqual(input,request);return result}}).resolve(request);assert.deepEqual(resolved,{startupBindingReceiptRef:startupRef,repositorySourceSnapshotReceiptRef:toolset.snapshotRef,toolsetValidationReceiptPointer:toolset.pointer})});
