import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fixture, prepareInput, session } from "./runIsolationTestHelpers.mjs";
import { DEPENDENCY_CONTRACT_MANIFEST } from "../src/runIsolation/dependencyContractManifest.mjs";

test("20 parallel Test Runs isolate SQLite WAL, cache, upload, queue, tmp, ports and cleanup",async t=>{const {service}=await fixture(t);const prepared=await Promise.all(Array.from({length:20},(_,i)=>service.prepareRun(prepareInput({idempotencyKey:`prepare-${i}`}),session)));assert.equal(new Set(prepared.map(x=>x.context.runRoot)).size,20);assert.equal(new Set(prepared.map(x=>x.context.databasePath)).size,20);assert.equal(new Set(prepared.map(x=>x.context.userDefaultsSuite)).size,20);assert.equal(new Set(prepared.map(x=>x.context.backendPort)).size,20);
  for(let i=0;i<prepared.length;i++){const c=prepared[i].context;const db=new DatabaseSync(c.databasePath);db.exec("PRAGMA journal_mode=WAL; CREATE TABLE isolated(value TEXT); INSERT INTO isolated VALUES ('run-"+i+"')");assert.equal(db.prepare("SELECT value FROM isolated").get().value,`run-${i}`);db.close();for(const dir of [c.cacheDir,c.tmpDir,c.uploadDir,c.queueDir,c.runtimeDir])await writeFile(join(dir,`run-${i}.txt`),c.runId)}
  const receipts=await Promise.all(prepared.map(async({context})=>{const run=service.store.getRun(context.runId);return service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:`cleanup-${run.runId}`},session)}));assert.equal(receipts.every(x=>x.outcome==="cleaned"),true);for(const {context} of prepared)await assert.rejects(access(context.runRoot),{code:"ENOENT"})});

test("content-addressed shared fixture remains unchanged across private overlays",async t=>{const {service}=await fixture(t);const content=Buffer.from("immutable fixture");const hash=createHash("sha256").update(content).digest("hex");const shared=join(service.binding.canonicalPath,"repositories","shared-test","shared","fixtures",hash);await mkdir(shared,{recursive:true});await writeFile(join(shared,"fixture.bin"),content);const before=createHash("sha256").update(await readFile(join(shared,"fixture.bin"))).digest("hex");const [a,b]=await Promise.all([service.prepareRun(prepareInput({idempotencyKey:"overlay-a"}),session),service.prepareRun(prepareInput({idempotencyKey:"overlay-b"}),session)]);await writeFile(join(a.context.dataDir,"overlay.bin"),"a");await writeFile(join(b.context.dataDir,"overlay.bin"),"b");assert.equal(createHash("sha256").update(await readFile(join(shared,"fixture.bin"))).digest("hex"),before);assert.notEqual(await readFile(join(a.context.dataDir,"overlay.bin"),"utf8"),await readFile(join(b.context.dataDir,"overlay.bin"),"utf8"))});

test("two source-aware Worktree Development roots isolate databases, defaults, ports and mutable data",async t=>{const contract=DEPENDENCY_CONTRACT_MANIFEST.repositorySourceSnapshot;const {service}=await fixture(t);const makeSnapshot=index=>({receiptId:`snapshot:${index}`,receiptHash:String(index).repeat(64),sourceFingerprint:createHash("sha256").update(`source-${index}`).digest("hex"),schemaVersion:1,resourceVersion:1,artifactRef:{artifactId:contract.artifactId,version:1,contentHash:contract.contentHash,relation:"implementation_spec",receiptType:contract.receiptType,schemaVersion:1}});const sessions=[{...session,repositoryId:"repository:development",worktreeId:"worktree:one"},{...session,repositoryId:"repository:development",worktreeId:"worktree:two"}];const prepared=await Promise.all(sessions.map((authenticated,index)=>service.prepareRun(prepareInput({mode:"development",sourceAware:true,idempotencyKey:`development-${index}`,repositorySourceSnapshotReceiptRef:makeSnapshot(index+1)}),authenticated)));assert.notEqual(prepared[0].context.runRoot,prepared[1].context.runRoot);assert.notEqual(prepared[0].context.databasePath,prepared[1].context.databasePath);assert.notEqual(prepared[0].context.userDefaultsSuite,prepared[1].context.userDefaultsSuite);assert.notEqual(prepared[0].context.backendPort,prepared[1].context.backendPort);for(let index=0;index<prepared.length;index++){const context=prepared[index].context;const db=new DatabaseSync(context.databasePath);db.exec(`CREATE TABLE isolated(value TEXT); INSERT INTO isolated VALUES ('worktree-${index}')`);db.close();await writeFile(join(context.cacheDir,"identity"),sessions[index].worktreeId)}assert.equal(await readFile(join(prepared[0].context.cacheDir,"identity"),"utf8"),"worktree:one");assert.equal(await readFile(join(prepared[1].context.cacheDir,"identity"),"utf8"),"worktree:two")});
