import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import { DataRootVerifier, deriveRunPaths } from "../src/runIsolation/dataRootVerifier.mjs";
import { fixture, prepareInput, session } from "./runIsolationTestHelpers.mjs";
import { resolveRunIsolationStorePaths } from "../src/store/corptieStore.mjs";

test("unavailable or non-external dataRoot fails closed without internal fallback",async t=>{const root=await mkdtemp("/Volumes/T9/corptie-root-reject-");t.after(()=>rm(root,{recursive:true,force:true}));const verifier=new DataRootVerifier({homeDirectory:"/Users/test",volumeInspector:async()=>({external:false,volumeUUID:null,mountPoint:null,filesystemType:null})});await assert.rejects(verifier.verify(root),{code:"DATA_ROOT_NOT_EXTERNAL"});assert.equal(await readFile(join(root,".corptie-data-root.json"),"utf8").catch(()=>null),null)});
test("dataRoot marker binds device, inode, volume and rejects remount identity changes",async t=>{const root=await mkdtemp("/Volumes/T9/corptie-root-bind-");t.after(()=>rm(root,{recursive:true,force:true}));let uuid="volume:a";const verifier=new DataRootVerifier({homeDirectory:"/Users/test",volumeInspector:async()=>({external:true,volumeUUID:uuid,mountPoint:"/Volumes/T9",filesystemType:"apfs"})});const first=await verifier.verify(root);assert.equal(first.volumeUUID,"volume:a");uuid="volume:b";await assert.rejects(verifier.verify(root),{code:"DATA_ROOT_IDENTITY_CHANGED"})});
test("run paths are deterministic and isolated by repository, worktree and run",async t=>{const {service}=await fixture(t);const one=deriveRunPaths(service.binding,{repositoryId:"repository:a",worktreeId:"worktree:a",runId:"run:a",mode:"test"});const two=deriveRunPaths(service.binding,{repositoryId:"repository:a",worktreeId:"worktree:b",runId:"run:a",mode:"test"});const three=deriveRunPaths(service.binding,{repositoryId:"repository:a",worktreeId:"worktree:a",runId:"run:b",mode:"test"});assert.notEqual(one.runRoot,two.runRoot);assert.notEqual(one.runRoot,three.runRoot);assert.match(one.runRoot,/repositories\/repository-[0-9a-f]{24}\/worktrees\/worktree-[0-9a-f]{24}\/test-runs\/run-[0-9a-f]{24}$/)});
test("prepared RunContext routes every mutable class under its run root",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput(),session);for(const path of [context.databasePath,context.dataDir,context.cacheDir,context.indexDir,context.tmpDir,context.logDir,context.uploadDir,context.queueDir,context.runtimeDir])assert.equal(path.startsWith(`${context.runRoot}/`),true,path);assert.match(context.userDefaultsSuite,/^com\.corptie\.run\./);assert.equal(process.env.HOME===undefined,false);assert.equal(context.runRoot.includes("/.corptie/"),false);const marker=JSON.parse(await readFile(join(context.runRoot,".run-owner.json"),"utf8"));assert.equal(marker.runId,context.runId)});
test("backend Store consumes explicit SQLite/WAL path and rejects missing or escaped paths before opening",()=>{const root="/Volumes/T9/runs/one";const valid={CORPTIE_RUN_ID:"run:one",CORPTIE_RUN_MODE:"test",CORPTIE_DATABASE_PATH:`${root}/database/corptie.sqlite`,CORPTIE_DATA_DIR:`${root}/data`,CORPTIE_CACHE_DIR:`${root}/cache`,CORPTIE_TMP_DIR:`${root}/tmp`,CORPTIE_LOG_DIR:`${root}/logs`,CORPTIE_UPLOAD_DIR:`${root}/uploads`,CORPTIE_QUEUE_DIR:`${root}/queues`,CORPTIE_RUNTIME_DIR:`${root}/runtime`};assert.equal(resolveRunIsolationStorePaths(valid).dbPath,`${root}/database/corptie.sqlite`);assert.throws(()=>resolveRunIsolationStorePaths({...valid,CORPTIE_DATABASE_PATH:undefined}),{code:"RUN_PATH_MISSING"});assert.throws(()=>resolveRunIsolationStorePaths({...valid,CORPTIE_CACHE_DIR:"/tmp/cache"}),{code:"RUN_PATH_OUT_OF_BOUNDS"})});
test("resolved Snapshot contract routes source-aware Runs through authoritative repository/worktree identity",async t=>{const manifest=(await import("../src/runIsolation/dependencyContractManifest.mjs")).DEPENDENCY_CONTRACT_MANIFEST;const snapshotContract=manifest.repositorySourceSnapshot;const {service}=await fixture(t);const sourceSession={...session,repositoryId:"repository:a",worktreeId:"worktree:a"};const snapshot={receiptId:"snapshot:1",receiptHash:"e".repeat(64),sourceFingerprint:"f".repeat(64),schemaVersion:1,resourceVersion:1,artifactRef:{artifactId:snapshotContract.artifactId,version:1,contentHash:snapshotContract.contentHash,relation:"implementation_spec",receiptType:"RepositorySourceSnapshotReceipt",schemaVersion:1}};const {context,receipt}=await service.prepareRun(prepareInput({sourceAware:true,repositorySourceSnapshotReceiptRef:snapshot}),sourceSession);assert.equal(context.repositoryId,sourceSession.repositoryId);assert.equal(context.worktreeId,sourceSession.worktreeId);assert.equal(context.sourceFingerprint,snapshot.sourceFingerprint);assert.equal(receipt.startupBindingReceiptRef.startupOperationId,"startup:test");assert.match(context.runRoot,/repositories\/repository-[0-9a-f]{24}\/worktrees\/worktree-[0-9a-f]{24}/)});
