import test from "node:test";
import assert from "node:assert/strict";
import { access, link, mkdir, rename, rm, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { SAFETY_CHECKS, validateReceipt } from "../src/runIsolation/receiptContracts.mjs";
import { fixture, prepareInput, session } from "./runIsolationTestHelpers.mjs";
import { RunIsolationJanitor } from "../src/runIsolation/runIsolationJanitor.mjs";
import { signReceipt } from "../src/runIsolation/receiptContracts.mjs";

test("successful cleanup requires all 14 proofs, removes only the run and idempotently replays",async t=>{const {service,root}=await fixture(t);const {context}=await service.prepareRun(prepareInput(),session);const run=service.store.getRun(context.runId);const request={runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-1"};const receipt=await service.cleanup(request,session);validateReceipt(receipt,"cleanup");assert.equal(receipt.outcome,"cleaned");assert.deepEqual(Object.keys(receipt.safetyChecks),SAFETY_CHECKS);assert.equal(Object.values(receipt.safetyChecks).every(x=>x.status==="passed"),true);assert.equal((await service.cleanup(request,session)).receiptId,receipt.receiptId);await assert.rejects(access(context.runRoot),{code:"ENOENT"});await access(`${root}/control/isolation.sqlite`)});
test("symlink proof failure quarantines and never deletes target or run root",async t=>{const {service,root}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-symlink"}),session);await symlink(root,join(context.cacheDir,"escape"));const run=service.store.getRun(context.runId);const receipt=await service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-symlink"},session);assert.equal(receipt.outcome,"quarantined");assert.notEqual(receipt.safetyChecks.noSymlink.status,"passed");await access(context.runRoot);await access(root)});
test("native openat proof rejects hardlinks and never unlinks the external name",async t=>{const {service,root}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-hardlink"}),session);const external=join(root,"external-evidence");await writeFile(external,"must survive");await link(external,join(context.cacheDir,"linked-evidence"));const run=service.store.getRun(context.runId);const receipt=await service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-hardlink"},session);assert.equal(receipt.outcome,"quarantined");assert.notEqual(receipt.safetyChecks.noHardlinkEscape.status,"passed");assert.equal(await (await import("node:fs/promises")).readFile(external,"utf8"),"must survive");await access(context.runRoot)});
test("failed and explicit pin retention are finite and auditable",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-retain"}),session);const run=service.store.getRun(context.runId);const receipt=await service.cleanup({runId:run.runId,policy:"failure_ttl",reason:"failure evidence",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"retain-1"},session);validateReceipt(receipt,"cleanup");assert.equal(receipt.outcome,"retained");assert.equal(receipt.retentionReason,"failure evidence");assert.ok(Date.parse(receipt.retainUntil)>Date.parse(receipt.finishedAt));assert.equal(Object.values(receipt.safetyChecks).every(x=>x.status==="not_applicable"),true)});
test("foreign, pidReused and indeterminate reconciliation can never validate cleaned",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-proof"}),session);const run=service.store.getRun(context.runId);const paths=(await import("../src/runIsolation/dataRootVerifier.mjs")).deriveRunPaths(service.binding,{repositoryId:null,worktreeId:null,runId:run.runId,mode:run.mode});for(const status of ["foreign","pidReused","indeterminate"]){const proof=await service.safeDeletion.prove({run,paths,ownerNonce:run.ownerNonce,fence:run.fencingToken});proof.processReconciliation=status;const result=await service.safeDeletion.execute({cleanupOperationId:`cleanup:${status}`,run,paths,proof});assert.equal(result.outcome,"quarantined")}});
test("soft and hard quota admission is explicit and hard quota rejects",async t=>{const {service}=await fixture(t);const janitor=new RunIsolationJanitor({service,softQuotaBytes:1,hardQuotaBytes:Number.MAX_SAFE_INTEGER});const audit=await janitor.assertAdmission(0);assert.equal(audit.softExceeded,true);const blocked=new RunIsolationJanitor({service,softQuotaBytes:1,hardQuotaBytes:1});await assert.rejects(blocked.assertAdmission(1),{code:"DATA_ROOT_QUOTA_EXCEEDED"})});
test("prepareRun enforces configured hard quota before allocating, binding a port or creating a Run",async t=>{const {service}=await fixture(t,{serviceOptions:{hardQuotaBytes:1}});await assert.rejects(service.prepareRun(prepareInput({idempotencyKey:"quota-reject"}),session),{code:"DATA_ROOT_QUOTA_EXCEEDED"});assert.equal(service.store.listRuns().length,0);assert.equal(service.portBroker.handles.size,0)});
test("cleanup unknown reconcile reuses operation id and fails closed until proof is restored",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-unknown"}),session);await symlink(service.binding.canonicalPath,join(context.cacheDir,"escape"));let run=service.store.getRun(context.runId);const quarantined=await service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-unknown",cleanupOperationId:"cleanup:unknown"},session);const unknown=signReceipt({...quarantined,outcome:"unknown",receiptHash:"0".repeat(64)},"cleanup");service.store.updateCleanup("cleanup:unknown",{state:"unknown",outcome:"unknown",receipt:unknown});await rm(join(context.cacheDir,"escape"));run=service.store.getRun(context.runId);const reconciled=await service.reconcile("cleanup:unknown",session);assert.equal(reconciled.cleanupOperationId,"cleanup:unknown");assert.equal(reconciled.outcome,"cleaned")});
test("cleanup unknown reconciles a crash after rename by proving and deleting the exact trash inode",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-trash-reconcile"}),session);await symlink(service.binding.canonicalPath,join(context.cacheDir,"escape"));let run=service.store.getRun(context.runId);await service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-trash",cleanupOperationId:"cleanup:trash-crash"},session);service.store.updateCleanup("cleanup:trash-crash",{state:"unknown",outcome:"unknown",receipt:null});await rm(join(context.cacheDir,"escape"));await mkdir(join(service.binding.canonicalPath,"trash"),{recursive:true});const trashPath=join(service.binding.canonicalPath,"trash","cleanup_trash-crash");await rename(context.runRoot,trashPath);run=service.store.getRun(context.runId);const previousFence=run.fencingToken;const reconciled=await service.reconcile("cleanup:trash-crash",session);assert.equal(reconciled.outcome,"cleaned");assert.ok(reconciled.fencingToken>previousFence);await assert.rejects(access(trashPath),{code:"ENOENT"});await assert.rejects(access(context.runRoot),{code:"ENOENT"})});
test("two concurrent Janitors produce one cleanup receipt without double deletion",async t=>{let now=new Date("2026-08-30T00:00:00.000Z");const {service}=await fixture(t,{clock:()=>new Date(now)});const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-double-janitor"}),session);let run=service.store.getRun(context.runId);await service.cleanup({runId:run.runId,policy:"cancelled_ttl",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"retain-double"},session);now=new Date("2026-08-31T00:00:00.000Z");const one=new RunIsolationJanitor({service,softQuotaBytes:Number.MAX_SAFE_INTEGER,hardQuotaBytes:Number.MAX_SAFE_INTEGER,clock:()=>new Date(now)});const two=new RunIsolationJanitor({service,softQuotaBytes:Number.MAX_SAFE_INTEGER,hardQuotaBytes:Number.MAX_SAFE_INTEGER,clock:()=>new Date(now)});const results=(await Promise.all([one.sweep(),two.sweep()])).flat();assert.equal(results.filter(receipt=>receipt.outcome==="cleaned").length,1);run=service.store.getRun(context.runId);assert.equal(run.state,"cleaned");assert.equal(service.store.db.prepare("SELECT COUNT(*) AS count FROM cleanup_receipts WHERE run_id=? AND receipt_json LIKE '%\"outcome\":\"cleaned\"%'").get(context.runId).count,1)});
