import test from "node:test";
import assert from "node:assert/strict";
import { fixture, prepareInput, session } from "./runIsolationTestHelpers.mjs";

test("allocated-preparing-ready and recoverable/orphaned paths use CAS and fencing",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput(),session);let run=service.store.getRun(context.runId);assert.equal(run.state,"ready");run=service.store.updateRun(run.runId,{expectedVersion:run.resourceVersion,fencingToken:run.fencingToken,fromStates:["ready"],state:"recoverable",patch:{outcome:"unknown",error:{code:"RUN_HEARTBEAT_EXPIRED"}}});assert.equal(run.state,"recoverable");run=service.store.updateRun(run.runId,{expectedVersion:run.resourceVersion,fencingToken:run.fencingToken,fromStates:["recoverable"],state:"orphaned"});assert.equal(run.state,"orphaned");const claimed=service.store.claimFence(run.runId,run.resourceVersion);assert.equal(claimed.fencingToken,run.fencingToken+1);assert.throws(()=>service.store.updateRun(run.runId,{expectedVersion:claimed.resourceVersion,fencingToken:run.fencingToken,fromStates:["orphaned"],state:"cleaning"}),{code:"RUN_STALE_FENCE"})});
test("prepare idempotency replays one run and conflicting payload is rejected",async t=>{const {service}=await fixture(t);const first=await service.prepareRun(prepareInput(),session);const replay=await service.prepareRun(prepareInput(),session);assert.equal(replay.replay,true);assert.equal(replay.context.runId,first.context.runId);await assert.rejects(service.prepareRun(prepareInput({quotaClass:"large"}),session),{code:"IDEMPOTENCY_CONFLICT"});assert.equal(service.store.listRuns().length,1)});
test("heartbeat rejects stale fence and cannot revive cleaned state",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput(),session);const before=service.store.getRun(context.runId);assert.throws(()=>service.heartbeat({runId:context.runId,fencingToken:99},session),{code:"RUN_STALE_FENCE"});const after=service.heartbeat({runId:context.runId,fencingToken:before.fencingToken},session);assert.ok(after.resourceVersion>before.resourceVersion)});
test("cancel follows ready-stopping-cleaning and idempotently replays its RunReceipt v6",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-cancel"}),session);const run=service.store.getRun(context.runId);const request={runId:run.runId,expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken};const receipt=await service.cancel(request,session);assert.equal(receipt.schemaVersion,6);assert.equal(receipt.state,"cancelled");assert.equal(receipt.outcome,"cancelled");assert.ok(receipt.stoppedAt);assert.ok(receipt.completedAt);assert.equal(service.store.getRun(run.runId).state,"cleaning");assert.equal((await service.cancel(request,session)).receiptId,receipt.receiptId)});
test("startup recovery marks expired active Runs orphaned exactly once",async t=>{let now=new Date("2026-08-30T00:00:00.000Z");const {service}=await fixture(t,{clock:()=>new Date(now)});const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-expiry"}),session);now=new Date("2026-08-30T00:01:00.000Z");const recovered=service.recoverExpiredRuns({heartbeatTimeoutMilliseconds:30_000});assert.equal(recovered.length,1);assert.equal(recovered[0].state,"orphaned");assert.equal(recovered[0].error.code,"RUN_HEARTBEAT_EXPIRED");assert.equal(service.recoverExpiredRuns({heartbeatTimeoutMilliseconds:30_000}).length,0);assert.equal(service.store.getRun(context.runId).state,"orphaned")});
test("control Store persists binding, port and retention contracts",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-control-schema"}),session);const tables=new Set(service.store.db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(row=>row.name));for(const name of ["data_root_bindings","port_leases","retention_policies","cleanup_receipts"])assert.equal(tables.has(name),true);assert.equal(service.store.db.prepare("SELECT COUNT(*) AS count FROM data_root_bindings WHERE state='verified'").get().count,1);assert.equal(service.store.db.prepare("SELECT COUNT(*) AS count FROM port_leases WHERE run_id=? AND state='active'").get(context.runId).count,1);assert.equal(service.store.db.prepare("SELECT max_pin_ttl_seconds FROM retention_policies WHERE policy_version='run-retention-v1'").get().max_pin_ttl_seconds,14*24*60*60)});
test("only one cleanup lease may claim a Run and old fences cannot continue",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-cleanup-claim"}),session);const run=service.store.getRun(context.runId);service.store.createCleanup({cleanupOperationId:"cleanup:first-claim",runId:run.runId,idempotencyKey:"first-claim",requestHash:"a".repeat(64),ownerNonce:run.ownerNonce,fence:run.fencingToken,expectedRunVersion:run.resourceVersion,startedAt:new Date().toISOString()});await assert.rejects(service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"second-claim",cleanupOperationId:"cleanup:second-claim"},session),{code:"RUN_CLEANUP_BLOCKED"});const claimed=service.store.claimFence(run.runId,run.resourceVersion);assert.throws(()=>service.heartbeat({runId:run.runId,fencingToken:run.fencingToken},session),{code:"RUN_STALE_FENCE"});assert.ok(claimed.fencingToken>run.fencingToken)});
