import test from "node:test";
import assert from "node:assert/strict";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { canonicalizeJson, cleanupReceiptSchema, receiptHash, runReceiptSchema, SAFETY_CHECKS, SAFETY_ERROR_CODES, signReceipt, toolsetValidationReceiptSchema, validateReceipt } from "../src/runIsolation/receiptContracts.mjs";
import { DEPENDENCY_CONTRACT_MANIFEST, projectToolsetValidationReceiptPointer, resolveToolsetValidationReceiptPointer, validateDependencyManifest, validateStageOwnership, validateStartupBindingReceipt, validateToolsetValidationReceiptPointer } from "../src/runIsolation/dependencyContractManifest.mjs";
import { fixture, prepareInput, session, startupRef } from "./runIsolationTestHelpers.mjs";

test("approved RunReceipt v6, CleanupReceipt v4 and ToolsetValidationReceipt v3 compile as JSON Schema 2020-12",()=>{const ajv=new Ajv2020({strict:false,allErrors:true});addFormats(ajv);for(const schema of [runReceiptSchema,cleanupReceiptSchema,toolsetValidationReceiptSchema]){assert.equal(ajv.validateSchema(schema),true);assert.equal(typeof ajv.compile(schema),"function");assert.equal(schema.additionalProperties,false)}assert.equal(runReceiptSchema.properties.schemaVersion.const,6);assert.equal(cleanupReceiptSchema.properties.schemaVersion.const,4);assert.equal(toolsetValidationReceiptSchema.properties.schemaVersion.const,3)});
test("RFC8785 canonicalization has deterministic golden vectors",()=>{assert.equal(canonicalizeJson({b:[true,null,1e30],a:"€"}),'{"a":"€","b":[true,null,1e+30]}');assert.equal(receiptHash({receiptHash:"f".repeat(64),b:2,a:1}),"43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777")});
test("fixed dependency manifest has exactly four resolved authorities and drift fails closed",()=>{assert.equal(validateDependencyManifest(),true);assert.equal(Object.keys(DEPENDENCY_CONTRACT_MANIFEST).length,4);assert.equal(Object.values(DEPENDENCY_CONTRACT_MANIFEST).every((entry)=>entry.status==="resolved"&&entry.approvalStatus==="approved"&&entry.versionPolicy==="fixed"),true);assert.throws(()=>validateDependencyManifest({...DEPENDENCY_CONTRACT_MANIFEST,legacy:{status:"resolved"}}),{code:"DEPENDENCY_CONTRACT_HASH_MISMATCH"});assert.throws(()=>validateDependencyManifest({...DEPENDENCY_CONTRACT_MANIFEST,runCleanup:{...DEPENDENCY_CONTRACT_MANIFEST.runCleanup,contentHash:"0".repeat(64)}}),{code:"DEPENDENCY_CONTRACT_HASH_MISMATCH"})});
test("full Toolset v3 receipt is dereferenced and reduced to the exact six-field Run v6 pointer",async t=>{const sourceFingerprint="d".repeat(64);const snapshotRef={receiptId:"snapshot:1",receiptHash:"e".repeat(64),sourceFingerprint,schemaVersion:1,resourceVersion:1,artifactRef:contractRef(DEPENDENCY_CONTRACT_MANIFEST.repositorySourceSnapshot)};const base={receiptId:"toolset_validation_receipt:test",receiptHash:"0".repeat(64),schemaVersion:3,resourceVersion:1,artifactRef:contractRef(DEPENDENCY_CONTRACT_MANIFEST.toolsetValidation),identity:{logicalSessionId:"logical:test",objectiveId:"objective:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",taskId:"task:test",repositoryId:"repository:a",worktreeId:"worktree:a",startupBindingRef:{artifactId:DEPENDENCY_CONTRACT_MANIFEST.startupBinding.artifactId,artifactVersion:1,artifactContentHash:DEPENDENCY_CONTRACT_MANIFEST.startupBinding.contentHash,startupOperationId:"startup:test",startupReceiptHash:"a".repeat(64)}},snapshotRef,toolsetVersion:`ptv1:${"b".repeat(64)}`,validationPlanIdentity:`vp1:${"c".repeat(64)}`,validationCacheKey:`tvck1:${"f".repeat(64)}`,actionReceipts:[],assertionReceipts:[],cacheDisposition:"stored",outcome:"passed",startedAt:"2026-08-29T23:59:00.000Z",finishedAt:"2026-08-29T23:59:30.000Z",expiresAt:"2026-08-30T01:00:00.000Z",error:null};base.receiptHash=receiptHash(base);const authority={logicalSessionId:"logical:test",taskId:"task:test",repositoryId:"repository:a",worktreeId:"worktree:a"};const pointer=projectToolsetValidationReceiptPointer(base,sourceFingerprint,authority,DEPENDENCY_CONTRACT_MANIFEST,new Date("2026-08-30T00:00:00.000Z"));assert.deepEqual(Object.keys(pointer),["receiptId","receiptHash","resourceVersion","toolsetVersion","validationPlanIdentity","sourceFingerprint"]);assert.equal(pointer.validationPlanIdentity.startsWith("vp1:"),true);assert.deepEqual(await resolveToolsetValidationReceiptPointer({pointer,resolver:async id=>id===base.receiptId?base:null,sourceFingerprint,authority,now:new Date("2026-08-30T00:00:00.000Z")}),pointer);const {service}=await fixture(t,{serviceOptions:{toolsetReceiptResolver:async id=>id===base.receiptId?base:null}});const prepared=await service.prepareRun(prepareInput({sourceAware:true,toolsetRequired:true,repositorySourceSnapshotReceiptRef:snapshotRef,toolsetValidationReceiptPointer:pointer,idempotencyKey:"prepare-toolset-v6"}),authority);assert.equal(prepared.receipt.schemaVersion,6);assert.deepEqual(prepared.receipt.toolsetValidationReceiptPointer,pointer);assert.deepEqual(prepared.context.toolsetValidationReceiptPointer,pointer);assert.throws(()=>validateToolsetValidationReceiptPointer({...pointer,evidenceHash:"e".repeat(64)},sourceFingerprint),{code:"RUN_TOOLSET_SCHEMA_INVALID"});await assert.rejects(resolveToolsetValidationReceiptPointer({pointer:{...pointer,receiptHash:"9".repeat(64)},resolver:async()=>base,sourceFingerprint,authority,now:new Date("2026-08-30T00:00:00.000Z")}),{code:"RUN_TOOLSET_RECEIPT_HASH_MISMATCH"})});
test("prepare rejects downstream-owned identities before any allocation",async t=>{const {service}=await fixture(t);for(const field of ["runId","path","port","pid","sourceFingerprint","observationId"]){await assert.rejects(service.prepareRun(prepareInput({[field]:"forbidden"}),session),{code:"RUN_CONTEXT_SCHEMA_UNSUPPORTED"})}assert.equal(service.store.listRuns().length,0)});
test("issued ready RunReceipt validates and every required field is enforced",async t=>{const {service}=await fixture(t);const {receipt}=await service.prepareRun(prepareInput(),session);validateReceipt(receipt,"run");for(const field of runReceiptSchema.required){const invalid=structuredClone(receipt);delete invalid[field];assert.throws(()=>validateReceipt(invalid,"run"),{code:"RECEIPT_SCHEMA_INVALID"},field)}const extra={...receipt,unknown:true};assert.throws(()=>validateReceipt(extra,"run"),{code:"RECEIPT_SCHEMA_INVALID"})});
test("plaintext run credential remains memory-only while Store persists the redacted context",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-secret"}),session);assert.ok(context.runToken.length>=32);const persisted=service.store.getRun(context.runId).runContext;assert.equal(Object.hasOwn(persisted,"runToken"),false);assert.equal(JSON.stringify(persisted).includes(context.runToken),false)});
test("receipt hash rejects field and array mutation",async t=>{const {service}=await fixture(t);const {receipt}=await service.prepareRun(prepareInput(),session);assert.throws(()=>validateReceipt({...receipt,resourceVersion:receipt.resourceVersion+1},"run"),{code:"RECEIPT_HASH_MISMATCH"});assert.throws(()=>validateReceipt({...receipt,eventRefs:[...receipt.eventRefs,"run_event:late"]},"run"),{code:"RECEIPT_HASH_MISMATCH"})});
test("all RunReceipt state branches are generated and validated",async t=>{const {service}=await fixture(t);const {receipt:ready}=await service.prepareRun(prepareInput(),session);const error={code:"RUN_HEARTBEAT_EXPIRED",message:"expired",traceId:null,detailsHash:null};const fixtures=[
  {...ready,state:"running",startedAt:"2026-08-30T00:00:01.000Z"},
  {...ready,state:"stopping",startedAt:"2026-08-30T00:00:01.000Z",error},
  {...ready,state:"completed",outcome:"passed",startedAt:"2026-08-30T00:00:01.000Z",stoppedAt:"2026-08-30T00:00:02.000Z",completedAt:"2026-08-30T00:00:03.000Z"},
  {...ready,state:"failed",outcome:"failed",stoppedAt:"2026-08-30T00:00:02.000Z",completedAt:"2026-08-30T00:00:03.000Z",error},
  {...ready,state:"cancelled",outcome:"cancelled",stoppedAt:"2026-08-30T00:00:02.000Z",completedAt:"2026-08-30T00:00:03.000Z"},
  {...ready,state:"recoverable",outcome:"unknown",error},
  {...ready,state:"orphaned",outcome:"unknown",error}
];for(const value of fixtures)validateReceipt(signReceipt({...value,receiptId:`${value.state}:receipt`,receiptHash:"0".repeat(64)},"run"),"run")});
test("each of 14 SafetyChecks independently prevents cleaned",async t=>{const {service}=await fixture(t);const {context}=await service.prepareRun(prepareInput({idempotencyKey:"prepare-proof-contract"}),session);const run=service.store.getRun(context.runId);const cleaned=await service.cleanup({runId:run.runId,policy:"success_default",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:"cleanup-proof-contract"},session);for(const name of SAFETY_CHECKS){const invalid=structuredClone(cleaned);invalid.safetyChecks[name]={status:"failed",errorCode:SAFETY_ERROR_CODES[name],evidenceHash:"b".repeat(64)};invalid.receiptHash="0".repeat(64);assert.throws(()=>signReceipt(invalid,"cleanup"),{code:"RECEIPT_SCHEMA_INVALID"},name)}});
test("Startup/Snapshot/Toolset/Run ownership boundaries reject later-stage IDs",()=>{for(const [stage,field] of [["startup","sourceFingerprint"],["startup","runId"],["startup","observationId"],["snapshot","runId"],["snapshot","observationId"],["run_isolation","observationId"]])assert.throws(()=>validateStageOwnership(stage,{[field]:"early"}),{code:"DEPENDENCY_STAGE_OWNERSHIP_CONFLICT"});assert.equal(validateStageOwnership("observability",{observationId:"observation:1"}),true)});
test("StartupBinding port compares fixed identity, binding generation, inventory and canonical hash",()=>{const base={schemaVersion:2,status:"ready",startupOperationId:"startup:1",objectiveId:"objective:1",taskId:"task:1",logicalSessionId:"logical:1",repositoryId:"repository:1",worktreeId:"worktree:1",canonicalWorktreePath:"/Volumes/T9/worktree",headIdentity:{kind:"branch",branch:"main"},providerBindingId:"binding:1",bindingGeneration:2,sourceCommitOid:"1".repeat(40),sourceTreeOid:"2".repeat(40),baseRef:"main",repositoryInventoryVersion:"inventory:1",workspaceResourceVersion:3,resourceVersion:4,providerContextHash:"c".repeat(64),toolContractHash:"d".repeat(64),instructionSourcesHash:"e".repeat(64),phaseTimestamps:{readyAt:"2026-08-30T00:00:00Z"},compensation:{status:"not_required"},error:null,receiptHash:"0".repeat(64)};base.receiptHash=receiptHash(base);const ref={...startupRef,startupOperationId:base.startupOperationId,receiptHash:base.receiptHash,resourceVersion:base.resourceVersion};const authority={objectiveId:base.objectiveId,taskId:base.taskId,logicalSessionId:base.logicalSessionId,repositoryId:base.repositoryId,worktreeId:base.worktreeId,providerBindingId:base.providerBindingId,bindingGeneration:2,repositoryInventoryVersion:base.repositoryInventoryVersion,workspaceResourceVersion:3,resourceVersion:4};assert.equal(validateStartupBindingReceipt(base,ref,authority),base);assert.throws(()=>validateStartupBindingReceipt({...base,bindingGeneration:1},ref,authority),{code:"DEPENDENCY_CONTRACT_HASH_MISMATCH"});assert.throws(()=>validateStartupBindingReceipt({...base,observationId:"early"},ref,authority),{code:"STARTUP_BINDING_IDENTITY_MISMATCH"})});

function contractRef(contract){return {artifactId:contract.artifactId,version:contract.version,contentHash:contract.contentHash,relation:"implementation_spec",receiptType:contract.receiptType,schemaVersion:contract.schemaVersion}}
