import { lstat, readdir } from "node:fs/promises";
import { join } from "node:path";
import { contractError } from "./receiptContracts.mjs";

export class RunIsolationJanitor {
  constructor({service,softQuotaBytes,hardQuotaBytes,clock=()=>new Date()}={}){this.service=service;this.softQuotaBytes=softQuotaBytes;this.hardQuotaBytes=hardQuotaBytes;this.clock=clock}
  async usage(){return directoryBytes(this.service.binding.canonicalPath)}
  async assertAdmission(estimatedBytes){const observed=await this.usage();const hard=Number.isFinite(this.hardQuotaBytes)?this.hardQuotaBytes:Number.POSITIVE_INFINITY;const soft=Number.isFinite(this.softQuotaBytes)?this.softQuotaBytes:Number.POSITIVE_INFINITY;if(observed+estimatedBytes>hard)throw contractError("DATA_ROOT_QUOTA_EXCEEDED","Hard quota rejects a new Run.");return {observedBytes:observed,estimatedBytes,softExceeded:observed+estimatedBytes>soft,hardExceeded:false,policyVersion:"run-retention-v1"}}
  async sweep(){const receipts=[];const now=this.clock().getTime();let observed=await this.usage();const soft=Number.isFinite(this.softQuotaBytes)?this.softQuotaBytes:Number.POSITIVE_INFINITY;const runs=this.service.store.listRuns().filter(run=>run.state!=="cleaned");const expired=runs.filter(run=>run.retainUntil&&Date.parse(run.retainUntil)<=now);const pressure=runs.filter(run=>!expired.includes(run)&&!run.pinned&&["cleaning","recoverable","orphaned"].includes(run.state));const candidates=[...expired.sort(byExpiry),...pressure.sort(byPressure)];for(const candidate of candidates){if(!candidate.retainUntil&&observed<=soft)break;const run=this.service.store.getRun(candidate.runId);if(!run||run.state==="cleaned")continue;try{const receipt=await this.service.cleanup({runId:run.runId,policy:"janitor_expiry",expectedResourceVersion:run.resourceVersion,fencingToken:run.fencingToken,idempotencyKey:`janitor:${run.runId}:${run.retainUntil??"quota"}`},{logicalSessionId:run.logicalSessionId,workItemId:run.workItemId});receipts.push(receipt);observed=Math.max(0,observed-(receipt.bytesReclaimed??0))}catch(error){if(!["RUN_CLEANUP_BLOCKED","RUN_STALE_VERSION","RUN_STALE_FENCE","RUN_CLEANED","IDEMPOTENCY_CONFLICT"].includes(error?.code))throw error}}return receipts}
}
async function directoryBytes(root){let total=0;async function walk(path){const info=await lstat(path);total+=info.size;if(info.isDirectory())for(const name of await readdir(path))await walk(join(path,name))}await walk(root);return total}
function byExpiry(a,b){return Date.parse(a.retainUntil)-Date.parse(b.retainUntil)||a.runId.localeCompare(b.runId)}
function byPressure(a,b){const rank=run=>run.outcome==="passed"?0:run.outcome==="cancelled"?1:run.outcome==="failed"?2:3;return rank(a)-rank(b)||Date.parse(a.createdAt)-Date.parse(b.createdAt)||a.runId.localeCompare(b.runId)}
