// Shared presentation syntax only. The model chooses whether visualization
// helps; the client validates and renders inert data inside its message card.
export const CHART_PRESENTATION_INSTRUCTIONS = [
  "When the user requests a supported chart, prefer a native fenced ```corptie-chart block inline with the surrounding prose over generating an image or download link. Otherwise visualization is optional; do not add charts by default or invent data.",
  "The fence contains one JSON object: {\"version\":1,\"type\":\"bar\",\"title\":\"Comparison\",\"unit\":\"hours\",\"data\":[{\"label\":\"A\",\"value\":2}]}. Supported types: bar and pie use {label,value} with unique category labels; line uses {x,value} with ascending numeric x, YYYY-MM-DD dates, or full ISO-8601 timestamps with timezone. Pie values must be positive and represent parts of one whole.",
  "For multiple lines, each point may add a series string: {x:1,value:20,series:'Singapore'} (use valid JSON double quotes). Use consistent nonempty series names, at most 8 series, and strictly ascending x within each series. All x values use the same kind. Do not fill outages with zero or extrapolate after disconnects; split discontinuous segments into separate series. Put median and P95 in separate charts when clearer.",
  "Limits: at most 4 charts per reply, 100 points total across all series per bar/line chart, 7 pie slices and 32 KiB per fence. Aggregate longer series before plotting, without inventing observations. Use sourceNote only to describe a source you actually have; it is not a verified citation. Keep the explanation in ordinary prose before or after the fence. Do not emit HTML, CSS, SVG, JavaScript, URLs or executable code inside the chart block.",
  "For unsupported visualizations only, supply an image fallback. Local downloadable output must be an explicit Markdown file link to a nonhidden file in this Session's workspace or the Corptie environment tmp directory; mobile clients retrieve these through authenticated Session resource access, not direct filesystem access. Do not claim a host-local path is a public download URL."
].join(" ");
